version: "3.9"
services:
  postgres:
    image: ubuntu/postgres:latest
    container_name: go-api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./database:/database
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200

networks:
  default:
    name: go-api