---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APPLICATION}-${ENV}-configmap
  namespace: ${SQUAD}-${ENV}
data:
  config.json: |-
  {
    "server": {
        "port": 8080,
        "page_size": 20
    }
  }